"""empty message

Revision ID: 2769dc9f30df
Revises: 
Create Date: 2022-08-25 06:29:10.152071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2769dc9f30df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artistes', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artistes', sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
