"""empty message

Revision ID: 612e25678e11
Revises: 
Create Date: 2022-08-20 22:58:54.466382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612e25678e11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('id_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_state'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artistes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id_city', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('genre', sa.PickleType(), nullable=False),
    sa.Column('facebook_link', sa.String(length=150), nullable=True),
    sa.Column('image_link', sa.String(length=150), nullable=True),
    sa.Column('web_link', sa.String(length=250), nullable=True),
    sa.Column('search_venues', sa.Boolean(), nullable=True),
    sa.Column('search_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_city'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_link'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.String(length=50), nullable=False),
    sa.Column('id_city', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.PickleType(), nullable=False),
    sa.Column('facebook_link', sa.String(length=150), nullable=True),
    sa.Column('image_link', sa.String(length=150), nullable=True),
    sa.Column('web_link', sa.String(length=250), nullable=True),
    sa.Column('search_talents', sa.Boolean(), nullable=True),
    sa.Column('search_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_city'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_link'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artiste_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artiste_id'], ['artistes.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    op.drop_table('venues')
    op.drop_table('artistes')
    op.drop_table('cities')
    op.drop_table('states')
    # ### end Alembic commands ###
